### ISSUE TITLE
New meter api endpoints

### ISSUE THREAD

**Issue by MartijnCharged** [PimDoos/sessypy#16]
There will be some shifting in the api's of the p1 and ct meter.
Previously documented api's will function for the foreseeable future, but will eventually fade out of existence.
The reason for the switch is to provide more data, and for the available data to be more accurate.

The following endpoint will be deprecated at some point (yes, these are the P1 AND CT endpoints).
- `/api/v1/p1/status`
- `/api/v1/p1/details`

The new endpoint for the P1 meter is: `/api/v2/p1/details`, and for the CT meter: `/api/v1/ct/details`.

Attached is the swagger documentation for the P1 meter V1.1.0, and CT meter V1.0.0.
To View the files head over to the [swagger editor](https://editor.swagger.io) and paste the txt files in (they are in txt couse github cant deal with yaml files, cause why would it).
[api_docs_ct.txt](https://github.com/PimDoos/sessypy/files/12488994/api_docs_ct.txt)
[api_docs_p1.txt](https://github.com/PimDoos/sessypy/files/12488995/api_docs_p1.txt)

**Comment by PimDoos** [comment]
Updated SessyApiCommand Enum with new endpoints. This will break on FW <1.5.2, so I will keep this on dev until FW 1.5.2 is publicly available.

**Comment by PimDoos** [comment]
Grid target implemented in dev.

**Comment by PimDoos** [comment]
Implemented in SessyPy 0.1.4

**Comment by PimDoos** [comment]
SessyPy 0.1.4 is released as a 'prerelease', will change this to 'latest' when Sessy FW 1.5.2 changes from Beta to Stable channel
