### ISSUE TITLE
Dynamic mode schedule and EPEX energy price api

### ISSUE THREAD

**Issue by MartijnCharged** [PimDoos/sessypy#29]
Dynamic schedules will be made available through the Sessy dongle at endpoint `api/v1/dynamic/schedule`, from Sessy dongle version 1.6.5.
[api_docs_dongle.txt](https://github.com/PimDoos/sessypy/files/14606427/api_docs_dongle.txt)

To View the file head over to the [swagger editor](https://editor.swagger.io/) and paste the txt files in (they are in txt becouse github can't deal with yaml files, cause why would it).

**Comment by bosgnoom** [comment]
Will this be available from `api/v1/dynamic/schedule` as written above (and api_docs_dongle.txt) or from `api/v2/dynamic/schedule` as from const.py?

**Comment by PimDoos** [comment]
Swagger file is the source of truth, so the sessypy version is currently incorrect. I'll fix it in a new version.
